### ISSUE TITLE
repacking/reuploading with identical recipient keys

### ISSUE THREAD

**Issue by KampfCaspar** [ansemjo/imap-reencrypt#1]
Currently, imap-reencrypt seems to repack and re-upload a message, even if the list of 'old recipients' and the list of 'new recipients' is identical.

It would be much lighter on use if it could check those lists on identity - and skip a message if re-encrypting is superfluous.

Use-Case: We must use a group e-mail address (on a server I cannot access otherwise) that multiple people access. Instead of distributing the one private key, I would run a cron job to  'continuously' re-encrypt the INBOX to all group members.

**Comment by ansemjo** [comment]
First of all it makes me happy that someone is actually using my script. :)

That sounds like an 'unfortunate' but interesting use-case. It should be fairly easy to implement that with a simple `set()`. I've learned a number of new things when implementing [imapfetch](https://github.com/ansemjo/imapfetch/) recently and might also add incremental checks for new mail etc. which would further quicken repeated executions. I'll take a look tomorrow!

**Comment by ansemjo** [comment]
This should have been fixed now and the script also uses the supposedly immutable `uid` instead of session-specific `id`.

Would a cache storing the highest-seen `uid` make sense to further speed things up?
